dir.create("9.cellchat")
scRNA_mnn <- SetIdent(scRNA_mnn, value = "new_celltype")
cellchat <- createCellChat(object = scRNA_mnn, group.by = "new_celltype")
CellChatDB <- CellChatDB.human 
CellChatDB.use <- CellChatDB
CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling")
cellchat@DB <- CellChatDB.use
showDatabaseCategory(CellChatDB.human)
cellchat <- CellChat::subsetData(cellchat) 
cellchat@data.signaling[1:10,1:10]
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
cellchat <- computeCommunProb(cellchat)
cellchat <- filterCommunication(cellchat, min.cells = 10)
cellchat <- computeCommunProbPathway(cellchat)
df.net <- subsetCommunication(cellchat,slot.name = "netP")
cellchat <- aggregateNet(cellchat)
groupSize <- as.numeric(table(cellchat@idents))
pdf("9.cellchat/cellchat_circle_count.pdf",width = 8,height = 4)
par(mfrow = c(1,2), xpd=TRUE)
netVisual_circle(cellchat@net$count, vertex.weight = groupSize, weight.scale = T,
                 label.edge= F, title.name = "Number of interactions")
dev.off()
pdf("9.cellchat/cellchat_circle_weight.pdf",width = 8,height = 4)
netVisual_circle(cellchat@net$weight, vertex.weight = groupSize, weight.scale = T, 
                 label.edge= F, title.name = "Interaction weights/strength")
dev.off()
cellchat@netP$pathways
pathways.show <- c("MIF") 
levels(cellchat@meta$celltype)
pdf("9.cellchat/cellchat_circle_aggregate.pdf",width = 8,height = 4)
par(mfrow=c(1,1))
netVisual_aggregate(cellchat, signaling = pathways.show, layout = "circle")
dev.off()
pdf("9.cellchat/cellchat_circle_aggregate_hierarchy.pdf",width = 8,height = 4)
vertex.receiver = seq(1,3)
netVisual_aggregate(cellchat, signaling = pathways.show, vertex.receiver = vertex.receiver, layout = "hierarchy")
dev.off()
pdf("9.cellchat/cellchat_circle_aggregate_chord.pdf",width = 8,height = 4)
netVisual_aggregate(cellchat, signaling = pathways.show, layout = "chord")
dev.off()
pdf("9.cellchat/cellchat_heatmap_count.pdf",width = 8,height = 4)
par(mfrow=c(1,1))
netVisual_heatmap(cellchat, measure = "count", color.heatmap = "Reds")
dev.off()
pdf("9.cellchat/cellchat_heatmap_weight.pdf",width = 8,height = 4)
par(mfrow=c(1,1))
netVisual_heatmap(cellchat, measure = "weight", color.heatmap = "Reds")
dev.off()
pdf("9.cellchat/cellchat_heatmap_pathways.pdf",width = 8,height = 4)
par(mfrow=c(1,1))
netVisual_heatmap(cellchat, signaling = pathways.show, color.heatmap = "Reds")
dev.off()
pdf("9.cellchat/cellchat_heatmap_pathways_centrality.pdf",width = 8,height = 4)
cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP")
netAnalysis_signalingRole_network(cellchat, signaling = pathways.show)
dev.off()
pdf("9.cellchat/cellchat_heatmap_pathways_centrality.pdf",width = 8,height = 4)
netAnalysis_signalingRole_scatter(cellchat)
dev.off()
pdf("9.cellchat/cellchat_heatmap_pathways_centrality.pdf",width = 8,height = 4)
ht1 <- netAnalysis_signalingRole_heatmap(cellchat, pattern = "outgoing")
ht2 <- netAnalysis_signalingRole_heatmap(cellchat, pattern = "incoming")
ht1 + ht2
dev.off()
pdf("9.cellchat/cellchat_bubble.pdf",width = 8,height = 4)
netVisual_bubble(cellchat, remove.isolate = FALSE, return.data = FALSE)
dev.off()
pdf("9.cellchat/cellchat_chord_gene.pdf",width = 8,height = 4)
netVisual_chord_gene(cellchat, lab.cex = 0.8,legend.pos.y = 50,legend.pos.x = 50)
dev.off()

#9.2 分别对各组cellchat进行细胞通讯分析
scRNA_mnn@meta.data %>% group_by(orig.ident,new_celltype) %>% summarise(n = n())
scRNA_mnn = subset(scRNA_mnn, 
                   new_celltype %in% c("EC1","EC3","EC4","FC1","FC2","FC3"))
scRNA_mnn@meta.data$celltype = droplevels(scRNA_mnn@meta.data$celltype)
sp <- SplitObject(scRNA_mnn, split.by = "orig.ident")
cellchat_A <- createCellChat(object = sp[["HNC01TIL"]], 
                             group.by = "new_celltype")
cellchat_B <- createCellChat(object = sp[["Tonsil2"]], 
                             group.by = "new_celltype")
cellchat_A@idents = droplevels(cellchat_A@idents)
cellchat_B@idents = droplevels(cellchat_B@idents)
cellchat_list= list()
for (i in c(cellchat_A,cellchat_B)){
  cellchat = i
  name = unique(i@meta$orig.ident)
  CellChatDB <- CellChatDB.human 
  CellChatDB.use <- CellChatDB
  cellchat@DB <- CellChatDB.use
  cellchat <- CellChat::subsetData(cellchat) 
  cellchat <- identifyOverExpressedGenes(cellchat)
  cellchat <- identifyOverExpressedInteractions(cellchat)
  cellchat <- computeCommunProb(cellchat)
  cellchat <- filterCommunication(cellchat, min.cells = 10)
  cellchat <- computeCommunProbPathway(cellchat)
  cellchat <- aggregateNet(cellchat)
  cellchat_list[[name]] = cellchat
}
cellchat <- mergeCellChat(cellchat_list , add.names = names(cellchat_list))
pdf("9.cellchat/cellchat_compare_interaction.pdf",width = 8,height = 4)
gg1 <- compareInteractions(cellchat, show.legend = F, group = c(1,2), measure = "count")
gg2 <- compareInteractions(cellchat, show.legend = F, group = c(1,2), measure = "weight")
gg1 + gg2
dev.off()
pdf("9.cellchat/cellchat_compare_interaction_diff.pdf",width = 8,height = 4)
netVisual_diffInteraction(cellchat, weight.scale = T,comparison = c(2,1))
netVisual_diffInteraction(cellchat, weight.scale = T, measure = "weight")
dev.off()
pdf("9.cellchat/cellchat_compare_interaction_heatmap.pdf",width = 8,height = 4)
gg1 <- netVisual_heatmap(cellchat)
gg2 <- netVisual_heatmap(cellchat, measure = "weight")
gg1+gg2
dev.off()